import { FiFilePlus, FiImage, FiFileText, FiScissors, FiMinimize2, FiRotateCw, FiLock, FiUnlock, FiEdit, FiList, FiGrid, FiTrash2, FiCheckSquare, FiType, FiLayout } from 'react-icons/fi';
import { FaSignature } from 'react-icons/fa';

export const tools = [
  {
    name: 'Merge PDF',
    title: 'PDF Merge',
    description: 'Combine multiple PDF files into a single document.',
    path: '/pdf-merge',
    icon: FiFilePlus,
    glow: 'from-cyan-400 to-blue-600',
  },
  {
    name: 'PDF to Image',
    title: 'PDF to Image',
    description: 'Convert PDF pages to high-quality images in various formats.',
    path: '/pdf-to-image',
    icon: FiImage,
    glow: 'from-emerald-400 to-emerald-600',
  },
  {
    name: 'Image to PDF',
    title: 'Image to PDF',
    description: 'Easily transform your images into a single PDF document.',
    path: '/image-to-pdf',
    icon: FiFileText,
    glow: 'from-pink-500 to-fuchsia-600',
  },
  {
    name: 'Split PDF',
    title: 'Split PDF',
    description: 'Divide a single PDF file into multiple smaller documents.',
    path: '/split-pdf',
    icon: FiScissors,
    glow: 'from-purple-400 to-violet-600',
  },
  {
    name: 'Compress PDF',
    title: 'Compress PDF',
    description: 'Reduce the size of your PDF files without losing quality.',
    path: '/compress-pdf',
    icon: FiMinimize2,
    glow: 'from-yellow-400 to-orange-600',
  },
  {
    name: 'Rotate PDF',
    title: 'Rotate PDF',
    description: 'Rotate PDF pages to the desired orientation (portrait or landscape).',
    path: '/rotate-pdf',
    icon: FiRotateCw,
    glow: 'from-green-400 to-lime-600',
  },
  {
    name: 'Protect PDF',
    title: 'Protect PDF',
    description: 'Add a password to encrypt and protect your PDF files.',
    path: '/protect-pdf',
    icon: FiLock,
    glow: 'from-red-400 to-rose-600',
  },
  {
    name: 'Unlock PDF',
    title: 'Unlock PDF',
    description: 'Remove password protection from your PDF files.',
    path: '/unlock-pdf',
    icon: FiUnlock,
    glow: 'from-indigo-400 to-purple-600',
  },
  {
    name: 'Edit PDF',
    title: 'Edit PDF',
    description: 'Basic text editing and markup features for your PDF documents.',
    path: '/edit-pdf',
    icon: FiEdit,
    glow: 'from-teal-400 to-cyan-600',
  },
  {
    name: 'Page Numbers',
    title: 'Page Numbers',
    description: 'Add page numbers to your PDF documents with custom formatting.',
    path: '/page-numbers',
    icon: FiList,
    glow: 'from-orange-400 to-red-600',
  },
  {
    name: 'Rearrange PDF',
    title: 'Rearrange PDF',
    description: 'Change the order of pages in your PDF document.',
    path: '/rearrange-pdf',
    icon: FiGrid,
    glow: 'from-blue-400 to-indigo-600',
  },
  {
    name: 'Remove Pages',
    title: 'Remove Pages',
    description: 'Remove specific pages or ranges from your PDF document.',
    path: '/remove-pages',
    icon: FiTrash2,
    glow: 'from-red-600 to-pink-700',
  },
  {
    name: 'Flatten PDF',
    title: 'Flatten PDF',
    description: 'Convert interactive form fields into static content.',
    path: '/flatten-pdf',
    icon: FiCheckSquare,
    glow: 'from-green-600 to-teal-700',
  },
  {
    name: 'Add Annotations',
    title: 'Add Annotations',
    description: 'Add simple text annotations to your PDF document.',
    path: '/add-annotations',
    icon: FiEdit,
    glow: 'from-purple-400 to-violet-600',
  },
  {
    name: 'Add Text Watermark',
    title: 'Add Text Watermark',
    description: 'Add a text watermark to your PDF document.',
    path: '/add-text-watermark',
    icon: FiType,
    glow: 'from-yellow-600 to-orange-700',
  },
  {
    name: 'PDF to Text',
    title: 'PDF to Text',
    description: 'Extract text content from your PDF document.',
    path: '/pdf-to-text',
    icon: FiFileText,
    glow: 'from-teal-400 to-green-600',
  },
  {
    name: 'Add Headers and Footers',
    title: 'Add Headers and Footers',
    description: 'Add custom headers and footers to your PDF document.',
    path: '/add-headers-footers',
    icon: FiLayout,
    glow: 'from-orange-500 to-pink-600',
  },
  {
    name: 'Add Image Signature',
    title: 'Add Image Signature',
    description: 'Add an image signature to your PDF document.',
    path: '/add-image-signature',
    icon: FaSignature,
    glow: 'from-purple-500 to-indigo-600',
  },
]; 